export interface PageInfo {
  id: string;
  title: string;
  desc: string;
  hue: number;
}

const PAGE_LIST: PageInfo[] = [
  { id: "001", title: " AB Test Results", desc: "Manage ab test results.", hue: 164 },
  { id: "002", title: "Ad Performance", desc: "Manage ad performance.", hue: 281 },
  { id: "003", title: "Affiliate Network", desc: "Manage affiliate network.", hue: 195 },
  { id: "004", title: "Analytics Dashboard", desc: "Manage analytics dashboard.", hue: 142 },
  { id: "005", title: "Api Documentation", desc: "Manage api documentation.", hue: 272 },
  { id: "006", title: "Asset Management", desc: "Manage asset management.", hue: 18 },
  { id: "007", title: "Audit Log Viewer", desc: "Manage audit log viewer.", hue: 330 },
  { id: "008", title: "Backup Restore", desc: "Manage backup restore.", hue: 85 },
  { id: "009", title: "Board Report", desc: "Manage board report.", hue: 210 },
  { id: "010", title: "Bounce Rate Analysis", desc: "Manage bounce rate analysis.", hue: 45 },
  { id: "011", title: "Branch Performance", desc: "Manage branch performance.", hue: 156 },
  { id: "012", title: "Browser Stats", desc: "Manage browser stats.", hue: 290 },
  { id: "013", title: "Budget Planning", desc: "Manage budget planning.", hue: 12 },
  { id: "014", title: "Bug Tracker", desc: "Manage bug tracker.", hue: 198 },
  { id: "015", title: "Business Continuity", desc: "Manage business continuity.", hue: 340 },
  { id: "016", title: "Cache Analytics", desc: "Manage cache analytics.", hue: 72 },
  { id: "017", title: "Chat Room", desc: "Manage chat room.", hue: 265 },
  { id: "018", title: "Churn Analysis", desc: "Manage churn analysis.", hue: 38 },
  { id: "019", title: "Code Review Queue", desc: "Manage code review queue.", hue: 175 },
  { id: "020", title: "Commission Report", desc: "Manage commission report.", hue: 310 },
  { id: "021", title: "Compliance Report", desc: "Manage compliance report.", hue: 95 },
  { id: "022", title: "Content Management", desc: "Manage content management.", hue: 225 },
  { id: "023", title: "Contract Library", desc: "Manage contract library.", hue: 55 },
  { id: "024", title: "Contract Renewals", desc: "Manage contract renewals.", hue: 150 },
  { id: "025", title: "Conversion Funnel", desc: "Manage conversion funnel.", hue: 285 },
  { id: "026", title: "Customer Insights", desc: "Manage customer insights.", hue: 22 },
  { id: "027", title: "Customer Segments", desc: "Manage customer segments.", hue: 178 },
  { id: "028", title: "Data Export", desc: "Manage data export.", hue: 332 },
  { id: "029", title: "Database Admin", desc: "Manage database admin.", hue: 68 },
  { id: "030", title: "Deal Tracker", desc: "Manage deal tracker.", hue: 245 },
  { id: "031", title: "Deployment History", desc: "Manage deployment history.", hue: 40 },
  { id: "032", title: "Device Breakdown", desc: "Manage device breakdown.", hue: 162 },
  { id: "033", title: "Disaster Recovery", desc: "Manage disaster recovery.", hue: 298 },
  { id: "034", title: "Email Campaigns", desc: "Manage email campaigns.", hue: 14 },
  { id: "035", title: "Employee Onboarding", desc: "Manage employee onboarding.", hue: 188 },
  { id: "036", title: "Executive Summary", desc: "Manage executive summary.", hue: 345 },
  { id: "037", title: "Expense Tracker", desc: "Manage expense tracker.", hue: 78 },
  { id: "038", title: "Feature Flags", desc: "Manage feature flags.", hue: 255 },
  { id: "039", title: "Feedback Survey", desc: "Manage feedback survey.", hue: 32 },
  { id: "040", title: "Geo Targeting", desc: "Manage geo targeting.", hue: 170 },
  { id: "041", title: "Goal Tracking", desc: "Manage goal tracking.", hue: 305 },
  { id: "042", title: "Hire Pipeline", desc: "Manage hire pipeline.", hue: 52 },
  { id: "043", title: "Incident Report", desc: "Manage incident report.", hue: 140 },
  { id: "044", title: "Inventory Overview", desc: "Manage inventory overview.", hue: 275 },
  { id: "045", title: "Investor Update", desc: "Manage investor update.", hue: 25 },
  { id: "046", title: "Invoice Manager", desc: "Manage invoice manager.", hue: 185 },
  { id: "047", title: "Kpi Dashboard", desc: "Manage kpi dashboard.", hue: 348 },
  { id: "048", title: "Language Distribution", desc: "Manage language distribution.", hue: 82 },
  { id: "049", title: "Lead Generation", desc: "Manage lead generation.", hue: 260 },
  { id: "050", title: "Leave Management", desc: "Manage leave management.", hue: 301 },
  { id: "051", title: "Lifetime Value", desc: "Manage lifetime value.", hue: 35 },
  { id: "052", title: "Load Test Results", desc: "Manage load test results.", hue: 165 },
  { id: "053", title: "Marketing Campaign", desc: "Manage marketing campaign.", hue: 295 },
  { id: "054", title: "Notification Center", desc: "Manage notification center.", hue: 48 },
  { id: "055", title: "Order Tracking", desc: "Manage order tracking.", hue: 132 },
  { id: "056", title: "Org Chart Viewer", desc: "Manage org chart viewer.", hue: 270 },
  { id: "057", title: "Os Analytics", desc: "Manage os analytics.", hue: 20 },
  { id: "058", title: "Overtime Report", desc: "Manage overtime report.", hue: 190 },
  { id: "059", title: "Page Views Heatmap", desc: "Manage page views heatmap.", hue: 342 },
  { id: "060", title: "Partner Portal", desc: "Manage partner portal.", hue: 88 },
  { id: "061", title: "Payroll Summary", desc: "Manage payroll summary.", hue: 250 },
  { id: "062", title: "Performance Metrics", desc: "Manage performance metrics.", hue: 30 },
  { id: "063", title: "Performance Review", desc: "Manage performance review.", hue: 155 },
  { id: "064", title: "Pipeline Forecast", desc: "Manage pipeline forecast.", hue: 280 },
  { id: "065", title: "Policy Library", desc: "Manage policy library.", hue: 58 },
  { id: "066", title: "Procurement Order", desc: "Manage procurement order.", hue: 145 },
  { id: "067", title: "Product Catalog", desc: "Manage product catalog.", hue: 268 },
  { id: "068", title: "Product Roadmap", desc: "Manage product roadmap.", hue: 28 },
  { id: "069", title: "Quality Control", desc: "Manage quality control.", hue: 182 },
  { id: "070", title: "Quarterly Forecast", desc: "Manage quarterly forecast.", hue: 335 },
  { id: "071", title: "Referral Program", desc: "Manage referral program.", hue: 92 },
  { id: "072", title: "Regional Sales", desc: "Manage regional sales.", hue: 242 },
  { id: "073", title: "Release Notes", desc: "Manage release notes.", hue: 42 },
  { id: "074", title: "Reseller Dashboard", desc: "Manage reseller dashboard.", hue: 160 },
  { id: "075", title: "Resource Allocation", desc: "Manage resource allocation.", hue: 288 },
  { id: "076", title: "Retention Cohorts", desc: "Manage retention cohorts.", hue: 16 },
  { id: "077", title: "Return Management", desc: "Manage return management.", hue: 175 },
  { id: "078", title: "Revenue Analysis", desc: "Manage revenue analysis.", hue: 320 },
  { id: "079", title: "Risk Assessment", desc: "Manage risk assessment.", hue: 65 },
  { id: "080", title: "Role Permissions", desc: "Manage role permissions.", hue: 235 },
  { id: "081", title: "Sales Report", desc: "Manage sales report.", hue: 46 },
  { id: "082", title: "Search Queries", desc: "Manage search queries.", hue: 152 },
  { id: "083", title: "Security Alerts", desc: "Manage security alerts.", hue: 292 },
  { id: "084", title: "Seo Rankings", desc: "Manage seo rankings.", hue: 10 },
  { id: "085", title: "Server Monitoring", desc: "Manage server monitoring.", hue: 195 },
  { id: "086", title: "Shift Scheduler", desc: "Manage shift scheduler.", hue: 338 },
  { id: "087", title: "Shipping Dashboard", desc: "Manage shipping dashboard.", hue: 75 },
  { id: "088", title: "Skill Matrix", desc: "Manage skill matrix.", hue: 258 },
  { id: "089", title: "Social Media Analytics", desc: "Manage social media analytics.", hue: 38 },
  { id: "090", title: "Sprint Planner", desc: "Manage sprint planner.", hue: 148 },
  { id: "091", title: "Stakeholder Map", desc: "Manage stakeholder map.", hue: 278 },
  { id: "092", title: "Store Locator", desc: "Manage store locator.", hue: 22 },
  { id: "093", title: "Subscription Plans", desc: "Manage subscription plans.", hue: 172 },
  { id: "094", title: "Succession Planning", desc: "Manage succession planning.", hue: 308 },
  { id: "095", title: "Support Tickets", desc: "Manage support tickets.", hue: 55 },
  { id: "096", title: "System Health", desc: "Manage system health.", hue: 228 },
  { id: "097", title: "Team Directory", desc: "Manage team directory.", hue: 48 },
  { id: "098", title: "Time On Site", desc: "Manage time on site.", hue: 142 },
  { id: "099", title: "Timesheet Approval", desc: "Manage timesheet approval.", hue: 285 },
  { id: "100", title: "Traffic Sources", desc: "Manage traffic sources.", hue: 15 },
  { id: "101", title: "Training Modules", desc: "Manage training modules.", hue: 185 },
  { id: "102", title: "User Management", desc: "Manage user management.", hue: 332 },
  { id: "103", title: "User Sessions", desc: "Manage user sessions.", hue: 65 },
  { id: "104", title: "Vendor Portal", desc: "Manage vendor portal.", hue: 248 },
  { id: "105", title: "Vendor Scorecard", desc: "Manage vendor scorecard.", hue: 38 },
  { id: "106", title: "Warehouse Map", desc: "Manage warehouse map.", hue: 155 },
  { id: "107", title: "Workflow Builder", desc: "Manage workflow builder.", hue: 275 },
  { id: "108", title: "Year End Review", desc: "Manage year end review.", hue: 12 },
];

export const PAGE_MAP = new Map(PAGE_LIST.map(p => [p.id, p]));
export const PAGE_IDS = PAGE_LIST.map(p => p.id);
